config/routes.rb
Rails.application.routes.draw do

  resources :settings
  resources :companies do
    resources :earnings
  end
  resources :queries

  get 'update_quotes', to: 'companies#update_quotes'
  
  root 'companies#index'

end

app/models/company.rb
require 'nokogiri'
require 'open-uri'

class Company < ActiveRecord::Base
  has_many :earnings, :dependent => :destroy
  has_many :dividends, :dependent => :destroy
  validates :ticker, presence: true, length: { minimum: 1 }

  def scrape
    a = 'casperjs '
    a += Rails.root.join('app/assets/javascripts/get_data.js').to_s
    a += ' ' + ticker.gsub('-','.')
    a += ' ' + Rails.root.to_s
    h = %x[ #{a} ]
    html = Nokogiri::HTML(h)

    self.name = html.css('div.wrapper div.r_bodywrap div.r_header div.reports_nav div.r_title h1')[0].content if html.css('div.wrapper div.r_bodywrap div.r_header div.reports_nav div.r_title h1')[0]
    if self.name.nil? || self.name.downcase.include?("pref share")
      self.no_data = true unless self.earnings.any?
    else
      self.bv_per_share = html.css('td[headers$="i8"]')[9].content.to_f if html.css('td[headers$="i8"]')[9]
      update_eps(html)
      update_div(html)
      self.last_earnings_update = Date.today
      self.require_update = false
    end
    self.save
  end

  def update_eps(html)
    titles = html.css('table.r_table1 thead tr th[id^="Y"]').map do |i|
      i.content
    end
    eps = html.css('td[headers$="i5"]').map do |i|
      i.content
    end

    if titles.length == 0
      self.no_data = true unless self.earnings.any?
    end

    unless titles.length == 0 || eps.length == 0
      earnings_per_share = Hash.new
      titles.each_with_index do |title, earnings|
        if title.include?('-')
          earnings_per_share[title] = eps[earnings].to_f unless eps[earnings].to_f == 0
        end
      end
      earnings_per_share.each do |eps|
        if self.earnings.where(year: eps[0]).empty?
          e = self.earnings.create
        else
          e = self.earnings.where(year: eps[0]).last
        end
        date = eps[0].split /-/
        e.year = date.first.to_i
        e.month = date.last.to_i
        e.value = eps[1]
        e.save
      end
    end
  end

  def update_div(html)
    titles = html.css('table.r_table1 thead tr th[id^="Y"]').map do |i|
      i.content
    end
    divs = html.css('td[headers$="i6"]').map do |i|
      i.content
    end

    unless titles.length == 0 || divs.length == 0
      dividends = Hash.new
      titles.each_with_index do |title, dividend|
        if title.include?('-')
          dateComponents = title.split /-/
          dividends[dateComponents[0].to_i] = divs[dividend].to_f unless divs[dividend].to_f == 0 
        end
      end
      dividends.each do |divs|
        if self.dividends.where(year: divs[0]).empty?
          d = self.dividends.create
        else
          d = self.dividends.where(year: divs[0]).last
        end
        d.year = divs[0]
        d.value = divs[1]
        d.save
      end
    end
  end

  def quote
    quote = YahooFinance::Client.new.quote(ticker)
    if !quote.nil? && (quote.exchange == 'NYQ' || quote.exchange == 'NMS')
      update_quote(quote)
    else
      #self.destroy
    end
  end

  def update_quote(quote)
    self.price = quote.regularMarketPrice.to_f
    self.price_change_pct = quote.regularMarketChangePercent.to_f
    self.market_cap_val = quote.marketCap.to_f
    bil = (quote.marketCap.to_f/1000000000).round 2
    mil = (quote.marketCap.to_f/1000000).round 2
    self.market_cap = bil.to_s + "B" if bil >= 1
    self.market_cap = mil.to_s + "M" if bil < 1

    if (self.no_data == false && self.last_earnings_update.nil?) ||
       (self.no_data == false && (Date.today > self.last_earnings_update + Setting.update_frequency_days.value.to_i.days))
      self.require_update = true
    else
      self.require_update = false
    end

    earnings = self.earnings.where('year >= ? AND year <= ?', Date.current.year - 6, Date.current.year).map { |e| e.value }
    average = (earnings.sum.round(3) / earnings.length).round(3) unless earnings.length == 0

    last_div = self.dividends.map{ |d| d.year }.max
    if self.dividends.where(year: last_div).any?
      dividend = self.dividends.where(year: last_div).last.value.to_f
    else
      dividend = 0.0
    end

    self.calculated_pe = self.price.to_f / average unless average.to_f == 0
    self.div_yield = dividend / self.price.to_f unless self.price.to_f == 0
    self.p_to_bv = self.price.to_f / self.bv_per_share.to_f unless self.bv_per_share.to_f == 0

    self.save
  end

end

app/controllers/companies_controller.rb
require 'financials'

class CompaniesController < ApplicationController

  def index
    @queries = Query.all

    scope = Company.all
    scope = scope.order(params[:sort] + ' ' + params[:direction]) if params[:sort].present? && params[:direction].present?
    scope = scope.where("lower(ticker) LIKE '#{params[:search].downcase}%' OR lower(name) LIKE '%#{params[:search].downcase}%'").order("ticker") if params[:search].present?
    if scope.count == 1
      redirect_to scope.first
    end
    if params[:query_id].present?
      @query = Query.find(params[:query_id])
      scope = build_query(scope, @query.id)
    end
    @companies = scope.paginate(:page => params[:page], :per_page => 30)
  end

  def build_query(scope, query_id)
    q = Query.find(query_id)
    query_params = {}
    query_params['min_pe'] = q.min_pe if q.min_pe
    query_params['max_pe'] = q.max_pe if q.max_pe
    query_params['min_p_to_bv'] = q.min_p_to_bv if q.min_p_to_bv
    query_params['max_p_to_bv'] = q.max_p_to_bv if q.max_p_to_bv
    query_params['min_div'] = q.min_div if q.min_div
    query_params['max_div'] = q.max_div if q.max_div
    query_params['min_cap'] = q.min_cap_val if q.min_cap_val
    query_params['max_cap'] = q.max_cap_val if q.max_cap_val
    query_params['favorites'] = q.favorites if q.favorites

    query = ''
    i = 0

    query_params.each do |param|
      query += 'calculated_pe >= ' + param[1].to_s if param[0] == 'min_pe'
      query += 'calculated_pe <= ' + param[1].to_s if param[0] == 'max_pe'
      query += 'p_to_bv >= ' + param[1].to_s if param[0] == 'min_p_to_bv'
      query += 'p_to_bv <= ' + param[1].to_s if param[0] == 'max_p_to_bv'
      query += '(div_yield*100) >= ' + param[1].to_s if param[0] == 'min_div'
      query += '(div_yield*100) <= ' + param[1].to_s if param[0] == 'max_div'
      query += 'market_cap_val >= ' + param[1].to_s if param[0] == 'min_cap'
      query += 'market_cap_val <= ' + param[1].to_s if param[0] == 'max_cap'
      query += 'favorite = 1' if param[0] == 'favorites' && q.favorites == true

      i += 1
      unless i >= query_params.length
        query += ' AND '
      end
    end
    scope = scope.where(query)
    scope = scope.order(q.sort_criteria) if q.sort_criteria
    scope
  end

  def show
    @company = Company.find(params[:id])

    @company.scrape if (@company.name.nil? || @company.updated_at.to_date <= (Date.today - 1.month))
    @company.quote
  end
  
  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to companies_path
    else
      render 'new'
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to company_path(@company)
    end
  end

private
  def company_params
    params.require(:company).permit(:ticker, :favorite, :comment, :no_data)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/index.html.erb
<div id="sidebar">
  <h3>Queries</h3>
  <ul>
  <% @queries.each do |q| %>
    <li><%= link_to q.name, {:controller => 'companies', :action => 'index', :query_id => q.id} %></li>
  <% end %>
  </ul>
  <p>
    <%= link_to 'New Query', new_query_path %>
  </p>
  <p>
    <%= link_to 'Settings', settings_path %>
  </p>
</div>

<div id="content">
  
  <% if @query %>
    <div id="actionmenu">
      <%= link_to 'Edit', edit_query_path(@query) %>
    </div>
    <h2><%= @query.name %></h2>
  <% end %>

  <table align="center">
    <thead>
      <th><%= sortable 'ticker' %></th>
      <th class="hiddencolumn"><%= sortable 'name' %></th>
      <th><%= sortable 'price' %></th>
      <th><%= sortable 'price_change_pct', 'Change' %></th>
      <th><%= sortable 'calculated_pe', 'P/E' %></th>
      <th><%= sortable 'p_to_bv', 'P/BV' %></th>
      <th><%= sortable 'div_yield', 'Yield' %></th>
      <th><%= sortable 'market_cap_val', 'Market Cap' %></th>
    </thead>
    <% @companies.each do |company| %>
      <% text_color = 'color: green !important;' if company.price_change_pct? && company.price_change_pct >= 0 %>
      <% text_color = 'color: red !important;' if company.price_change_pct? && company.price_change_pct < 0 %>
      <tr>
        <td><%= link_to company.ticker, company %></td>
        <td class="hiddencolumn" style="text-align: left;"><%= company.name %></td>
        <td><%= number_with_precision(company.price, precision: 2) if company.price? %></td>
        <td style='<%= text_color %>'><%= number_to_percentage(company.price_change_pct, precision: 2) if company.price_change_pct? %></td>
        <td><%= number_with_precision(company.calculated_pe, precision: 1) if company.calculated_pe? %></td>
        <td><%= number_with_precision(company.p_to_bv, precision: 1) if company.bv_per_share? %></td>
        <td><%= number_to_percentage(company.div_yield * 100, precision: 2) if company.div_yield? %></td>
        <td><%= company.market_cap if company.market_cap? %></td>
      </tr>
    <% end %>
  </table>
  <p>
  <%= will_paginate @companies %>
  </p>
</div>

app/views/companies/show.html.erb
<div id="sidebar">
  <h3>Details</h3>
  <ul>
    <li><%= link_to 'Yahoo Quote', 'http://finance.yahoo.com/q?s=' + @company.ticker.to_s, :target => '_blank' %></li>
    <li><%= link_to 'Google Quote', 'https://www.google.com/finance?q=' + @company.exchange.to_s + ':' + @company.ticker.gsub('-','.'), :target => '_blank' %></li>
    <li><%= link_to 'Morningstar Financials', 'http://financials.morningstar.com/ratios/r.html?t=' + @company.ticker.gsub('-','.'), :target => '_blank' %></li>
    <li><%= link_to 'SEC Form 10-k', 'http://www.sec.gov/cgi-bin/browse-edgar?type=10-k&Find=Search&owner=exclude&action=getcompany&CIK=' + @company.ticker.to_s.gsub('-',''), :target => '_blank' %></li>
  </ul>
</div>

<div id="content">
  <div id="actionmenu">
    <%= link_to 'Back', root_url %>
  </div>
  
  <h2><%= @company.name %></h2>

  <% years = [] %>
  <% years[0] = Date.current.year %>
  <% years[1] = (Date.current - 1.year).year %>
  <% years[2] = (Date.current - 2.year).year %>
  <% years[3] = (Date.current - 3.year).year %>
  <% years[4] = (Date.current - 4.year).year %>
  <% years[5] = (Date.current - 5.year).year %>
  <% years[6] = (Date.current - 6.year).year %>
  <% years[7] = (Date.current - 7.year).year %>

  <% text_color = 'color: green !important;' if @company.price_change_pct? && @company.price_change_pct >= 0 %>
  <% text_color = 'color: red !important;' if @company.price_change_pct? && @company.price_change_pct < 0 %>

  <table align="center" style='text-align: left;'>
    <tr style="background-color: #fff;">
      <td><strong>Ticker</strong></td>
      <td><strong><%= @company.ticker %></strong></td>
      <td><strong>P/E</strong></td>
      <td><%= number_with_precision(@company.calculated_pe, precision: 1) %></td>

    </tr>
    <tr style="background-color: #fff;">
      <td><strong>Exchange</strong></td>
      <td><%= @company.exchange %></td>
      <td><strong>Div Yield</strong></td>
      <td><%= number_to_percentage(@company.div_yield * 100, precision: 2) if @company.div_yield?%></td>

    </tr>
    <tr style="background-color: #fff;">
      <td><strong>Price</strong></td>
      <td><%= number_with_precision(@company.price, precision: 2) %></td>
      <td><strong>Book Value Per Share</strong></td>
      <td><%= number_with_precision(@company.bv_per_share, precision: 2) %></td>


    </tr>
    <tr style="background-color: #fff;">
      <td><strong>Change</strong></td>
      <td style='<%= text_color %>'><%= number_to_percentage(@company.price_change_pct, precision: 2) if @company.price_change_pct?%></td>
      <td><strong>Price to Book Value</strong></td>
      <td><%= number_with_precision(@company.p_to_bv, precision: 2) %></td>
    </tr>
    <tr style="background-color: #fff;">
      <td><strong>Market Cap</strong></td>
      <td><%= @company.market_cap %></td>
      <td></td>
      <td></td>
    </tr>
  </table>

  <br>

<% if @company.no_data %>
No data.
<% else %>

  <table align="center">
    <thead>
      <th>Financials</th>
      <% years.each do |year| %>
        <th><%= year.to_s %></th>
      <% end %>
    </thead>
    <tr>
      <td><strong>Earnings Per Share</strong></td>
      <% years.each do |year| %>
        <td><%= @company.earnings.where(year: year).last.value unless @company.earnings.where(year: year).empty? %></td>
      <% end %>
    </tr>
    <tr>
      <td><strong>Dividends</strong></td>
      <% years.each do |year| %>
        <td><%= @company.dividends.where(year: year).last.value unless @company.dividends.where(year: year).empty? %></td>
      <% end %>
    </tr>
  </table>

<% end %>

  <%= form_for :company, url: company_path(@company), method: :patch do |f| %>
    <p>
      <%= f.label 'Comments' %><br>
      <%= f.text_area :comment, size: '40x10' %>
    </p>
    <p>
      <%= f.label :favorite %>:
      <%= f.check_box :favorite %>
    </p>
    <p>
      <%= f.label 'Ignore' %>
      <%= f.check_box :no_data %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

  <% unless @company.last_earnings_update.nil? %>
  <p>
    Last earnings update: <%= @company.last_earnings_update %>
  </p>
  <% end %>
  <% unless @company.earnings.last.nil? %>
  <p>
    Last earnings value added on: <%= @company.earnings.last.created_at.to_date %> (<%= @company.earnings.last.year %>)
  </p>
  <% end %>

</div>