config/routes.rb
Rails.application.routes.draw do

  resources :settings
  resources :companies do
    resources :earnings
  end
  resources :queries

  get 'update_quotes', to: 'companies#update_quotes'
  
  root 'companies#index'

end

app/models/query.rb
class Query < ActiveRecord::Base
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    @queries = Query.all
  end

  def new
    @query = Query.new
  end

  def create
    @query = Query.new(query_params)

    if @query.save
      redirect_to companies_path(query_id: @query.id)
    else
      render 'new'
    end
  end

  def destroy
    @query = Query.find(params[:id])
    @query.destroy
    redirect_to companies_path
  end

  def edit
    @query = Query.find(params[:id])
  end

  def update
    @query = Query.find(params[:id])

    if @query.update(query_params)
      redirect_to companies_path(query_id: @query.id)
    else
      render 'edit'
    end
  end

private
  def query_params
    params.require(:query).permit(:name, :min_pe, :max_pe, :min_p_to_bv, :max_p_to_bv, :min_div, :max_div, :favorites, :sort_criteria, :min_cap_val, :min_cap_order, :max_cap_val, :max_cap_order)
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/edit.html.erb
<div id="content">
  <div id="actionmenu">
    <%= link_to 'Back', {:controller => 'companies', :action => 'index', :query_id => @query.id} %>
  </div>

  <h2>Edit Query</h2>

  <%= form_for :query, url: query_path(@query), method: :patch do |f| %>

    <table align="center">
      <thead>
        <th><%= f.label 'Query Name:' %></th>
        <th><%= f.text_field :name %></th>
      </thead>
        <td><%= f.label 'Min PE:' %></td>
        <td><%= f.text_field :min_pe %></td>
      <tr>
        <td><%= f.label 'Max PE:' %></td>
        <td><%= f.text_field :max_pe %></td>
      </tr>
        <td><%= f.label 'Min Price/Book Value:' %></td>
        <td><%= f.text_field :min_p_to_bv %></td>
      <tr>
        <td><%= f.label 'Max Price/Book Value:' %></td>
        <td><%= f.text_field :max_p_to_bv %></td>
      </tr>
      <tr>
        <td><%= f.label 'Min Dividend Yield:' %></td>
        <td class="nowrap"><%= f.text_field :min_div %>%</td>
      </tr>
      <tr>
        <td><%= f.label 'Max Dividend Yield:' %></td>
        <td class="nowrap"><%= f.text_field :max_div %>%</td>
      </tr>
      <tr>
        <td><%= f.label 'Min Market Cap:' %></td>
        <td class="nowrap"><%= f.text_field :min_cap_val %></td>
      </tr>
      <tr>
        <td><%= f.label 'Max Market Cap:' %></td>
        <td class="nowrap"><%= f.text_field :max_cap_val %></td>
      </tr>
      <tr>
        <td><%= f.label 'Only Show Favorites:' %></td>
        <td><%= f.check_box :favorites %></td>
      </tr>
      <tr>
        <td><%= f.label 'Sort By:' %></td>
        <td><%= f.select :sort_criteria, options_for_select(Company.attribute_names, @query.sort_criteria) %></td>
      </tr>
    </table>
    <p>
      <%= f.submit %>
    </p>
    
  <% end %>
</div>

app/views/queries/new.html.erb
<div id="content">
  <div id="actionmenu">
    <%= link_to 'Back', {:controller => 'companies', :action => 'index', :query_id => @query.id} %>
  </div>

  <h2>New Query</h2>

  <%= form_for :query, url: queries_path do |f| %>

    <table align="center">
      <thead>
        <th><%= f.label 'Query Name:' %></th>
        <th><%= f.text_field :name %></th>
      </thead>
        <td><%= f.label 'Min PE:' %></td>
        <td><%= f.text_field :min_pe %></td>
      <tr>
        <td><%= f.label 'Max PE:' %></td>
        <td><%= f.text_field :max_pe %></td>
      </tr>
        <td><%= f.label 'Min Price/Book Value:' %></td>
        <td><%= f.text_field :min_p_to_bv %></td>
      <tr>
        <td><%= f.label 'Max Price/Book Value:' %></td>
        <td><%= f.text_field :max_p_to_bv %></td>
      </tr>
      <tr>
        <td><%= f.label 'Min Dividend Yield:' %></td>
        <td class="nowrap"><%= f.text_field :min_div %>%</td>
      </tr>
      <tr>
        <td><%= f.label 'Max Dividend Yield:' %></td>
        <td class="nowrap"><%= f.text_field :max_div %>%</td>
      </tr>
      <tr>
        <td><%= f.label 'Min Market Cap:' %></td>
        <td class="nowrap"><%= f.text_field :min_cap_val %></td>
      </tr>
      <tr>
        <td><%= f.label 'Max Market Cap:' %></td>
        <td class="nowrap"><%= f.text_field :max_cap_val %></td>
      </tr>
      <tr>
        <td><%= f.label 'Only Show Favorites:' %></td>
        <td><%= f.check_box :favorites %></td>
      </tr>
      <tr>
        <td><%= f.label 'Sort By:' %></td>
        <td><%= f.select :sort_criteria, options_for_select(Company.attribute_names) %></td>
      </tr>
    </table>
    <p>
      <%= f.submit %>
    </p>
    
  <% end %>
  <p>
    <%= link_to 'Back', queries_path %>
  </p>
</div>